image: Visual Studio 2019
before_build:
  - git checkout master
  - IncreaseBuild.bat
  
build_script:
   - msbuild build.proj
   
on_success:
  - git status
  - git add .
  - git commit -m 'CI Build'
  - git status
  - git push
  