name: On Push Workflow
on: push

jobs:
  Increase-Version-Number:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Running Increase-Build.ps1
      shell: pwsh
      run: |
        .\_scripts\Increase-Build.ps1
    - name: commit changes
      run: |
        git config --global user.email "ci@github.com"
        git config --global user.name "CI"
        git add .
        git commit -m 'build number'
        git push
