name: Versioning

on: push

jobs:
  Versioning:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Running Increase-Build.ps1
      shell: pwsh
      run: |
        .\_scripts\Increase-Build.ps1
        
    - name: Commit Changes
      run: |
        git config --global user.email "Versioning@example.com"
        git config --global user.name "Versioning"
        git add .
        git commit -m 'build number'
        git push
