name: On Push Workflow
on: push

jobs:
  pester-test:
    name: Increase version number
    runs-on: ubuntu-latest
    steps:
    - name: Running IncreaseBuild.bat
      shell: pwsh
      run: |
        IncreaseBuild.bat