name: learn-github-actions
on: [push]
jobs:
  IncreaseBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: Amadevus/pwsh-script@v2.0.0
    with:
        # PowerShell script to execute in Actions-hydrated context
        script: .\IncreaseBuild.bat
